[package]
name = "cch23-brianheckel"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.0", features = ["macros"] }
axum-extra = { version = "0.9.0", features = ["cookie"] }
base64 = "0.21.5"
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
shuttle-axum = { version = "0.35.0", default-features = false, features = [
  "axum-0-7",
] }
shuttle-runtime = "0.35.0"
tokio = "1.28.2"
tracing = "0.1.40"
